name: 9
timestamp: 1500890567
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1500890567
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
